database:
  user: hanko
  password: hanko
  host: 10.0.0.205
  port: 5432
  dialect: postgres
smtp:
    host: smtp.example.com
    user: example
    password: example
passcode:
  email:
    from_address: no-reply@hanko.io
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Hanko Authentication Service
webauthn:
  relying_party:
    id: "10.0.0.205"
    display_name: "Hanko Authentication Service"
    origins:
      - "http://10.0.0.205"
