database:
  user: hanko
  password: hanko
  host: postgresd
  port: 5432
  dialect: postgres
smtp:
  host: "mailslurper"
  port: "2500"
passcode:
  email:
    from_address: no-reply@hanko.io
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Hanko Authentication Service
webauthn:
  relying_party:
    origins:
      - "http://10.0.0.205:8888"
      - "http://10.0.0.205:8000" 
session:
  cookie:
    secure: false # is needed for safari, because safari does not store secure cookies on localhost
server:
  public:
    cors:
      allow_origins:
        - "http://10.0.0.205:8888"
        - "http://10.0.0.205:8000"
